// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class addedUsersInRole : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207222115034_addedUsersInRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1d3W7cNha+X6DvIOiqu0BnnGwX6AbjFlk77gZbx4bHCbBXAS1xxkQlSpU4rv1se7GP1FcoJY00FMlDUdLoZ9LeBBmRPDw85+PfIT/6t//9f/XDcxg4TzhJSUTP3VeLM9fB1It8Qrfn7o5tvvnO/eH7r/6yeueHz86nMt/fs3y8JE3P3UfG4jfLZeo94hCli5B4SZRGG7bwonCJ/Gj5+uzsn8tXr5aYi3C5LMdZ3e0oIyHOf/CfFxH1cMx2KLiOfByk++88ZZ1LdT6gEKcx8vC5e8s1+2+0S26R9zPa4sVlFCJCF++4QEZw6jpvA4K4WmscbFwn/vbNxxSvWRLR7TpGjKDg/iXGPH2DghTvG/Em/ta2HWevs3YsEaUR4+Ii2skObtVC3sZc9ZdMrbydvIlF07IvYkae9T/4pfaBf7pNohgn7OUOb/bFeSbXWdYLLuWSVTmxUFbjufvjjviu82EXBOghwJWllsby2b+lAG5u7iTXuSLP2P8J0y17rKRco+fyyz84hj5SwsHGy7Bkh1tXepFgxLB/Q8uaL/nPexJaSPqAnsg2d6Akc2/824R4GZrucJDnSh9JXIBqIeb4LPrKuUqi8C4KJClins/3KNlixvWNGjKuOca9FnqvuYIhpkyvc5kK6atLV3TVZtLpuVoeMG2D9Lz1JwN1ofV9RX1CAfEzL7QHsE7SPQmC3pIG7FQF6o7dpUoENnapEs+doFqC/9RgusbUx8mRhN1hD5Ono4nr1IWaQFY02ASzIsdnYcRUUCZngcZtJV/bYVsyrEntMo9RcTUTpLomZ0flwW7dadaRu7Nxamo7O675og2Y1mtZKqPo1K3nAKdJKdsxJso9tmc7BHVcnfTol8DgD/bfPtavOuls7T+HRfl6l9BR6u0Htq6jKQA4w7jba7mRDyInA7hS6+MPHMcdsqE5BhjZO3nwY/rnSGGu9N8ofcT+LUrTX6PEb1k9/2/vkQoFbPxae+yv"
                       + "JEk/oZR9jP1maYWetl0uA+57mnUM/QB6SP+cY1zoblKSsjSS03utiQ7CTqabZSr3lZE1+Hjja+HBfl6WR1MIBbY65S7V6VSJrOB5UEpOU7CnZOgFvpOC3Tije+cBpZVbZbCBfrdx69s0jTyS66OJSNa2rfW2vqO+YxuWKswuh7m4tXcBI3FAPK7Yufs3xZ4WdVQYV+oottr1Kl65Mj5v6CUOMMPOW4/lBzsXKPWQr/qW28+vf+GQxglfJBEUXHBvsgQRylT8E+qRGAWWDZHK2/agTMGqKjnlEsfZZpAyS4fZ6CDHr1R1qlolOzaZbbUUMGkFVWXX3IAieAutgKgMpQ0Io2b1NBg/rPSb+lAflEKGGhGkkDFaYFSI/06JUs12uwEIpr23gtRD/HRMrJqCrWOjFTbXiHiFDdICsbVDhkkwq41bQ1gwB7G7wKBB9qlN+qZGjIFNk4NOZrIHQl1NwIHiXiosi0BjB2xCpyHNyJ8PNPVtGBOcekfZaFCLuU6CTTlUACEGjBscoCLEdFpAEQw71QXPD3+A4mMAD3CGTdVVFGsStCnRAggVcOjgAAsd0gZaM8IBqm7w7wQ4yCZjIA4ygE3dVdBzBMgVoSJehvESONlrUF4wzb7jZ3XmzcqsMVPXDKnrHIJPuvWaMqxpRZUXEiFZ+6BSgzDhsFMRdJim7TQqdpYGlcrwgZ24ctlvEHjY5Vk2M5tVd6nWbNK6p0FgBludlGJasShchTa1Iso+3yAIEqEtLKBbD6b6rRwhe9OlPLkLtgiGVi1ScK107BbhT1XqvuPJw3PdJvb2Um+mgOYyh+NaBeTUZlVdrtlaYBxNkCq051iW0l2rAG3VFBRqGRZS7SWMKc0WM0RzBrKZ/n6caq7meIR9RMKmKfYxiOF6HnS3A7aOaWvcZnOssdBhHrEwFLAhHghDyjmtaiDj/sxqhyboXpvMDNaA9mSSqGOYQD0/VG1g3jXY7RsE1ZvbDy737WxpMEN5mFmt"
                       + "UKu01bLgS+0/rJYAsWp1jeKY0K1AtNp/cdYFy+rim3V7YlNYyFh6NevK6+mqJhYlfLyQUnnVXNMrkqTsEjH0gLKD5gs/VLJZrsfL2jTLctV35bKqLJT9f1/QzDpbGAbmg3GveHuzbp83HeuHTrW0k7HgUIAS3aWAiyjYhdSwP4PLF5cCRAHFF3sJwk0mUYzwWZW1WkrGUPZzihuULXbdtW0cv19sDuB5DYWpjeuB4kP5Xg5pi6Kawt2wVIHNJAoUPreUVfCZFFnF5y8Sp6aFcHeMQmsiC3zCRQfGpnBurUGn4VS7UXLtfFEj23j+2Ci9Y5+adlws95UDDIw6yooV8hrK94XftAY/bEwHMLmep9LG6LCE+a5GKt6JKKT6OBsAKFvKIQZ6DWvEyv0N5Ydyfu0Is+Y+09nmZC4s9q3H9JtuW27hLn2x+XZRmfAhypLTWqAnp3HUYJN/GXaBCMmSSBmiPClpVniGwyL9UK0jaOSCbbANFR4K4dXBtigDPO2G5VSnlaIc8AhzMr8f3+MdfT2ul+3HsUH9ooTx5CxV7VU4TwrbrfYhtOZHk5SYWpHFdbhpnoifxdPWLynD4SLLsFj/ElwEJA+3lxmuESUbnLL76GdMz93XZ2ffSU8tdXgGaZmmfjDrt5B2lPyywyS7XkA2JAuv96De0CeUeI8oUYg2fRmE2ZTCmhmEJ/MsT2+r698X6S1Wea7Hz+8O9H2qp5OUwUEw5YM3xwKA8vjNsQRrHsKZB2hP50WRgRs25WMds5w1pHc5uok9nfcrevtA85bFUJCd6qmIWeJU/ypEKf3rED3/tddLD/0kdZ12VUna1xt00tTXG07kiYTe8JKeS+gtT3o6YajufLL27t+dhyfaF3fkJuC+6e+j9uD392F7AhdNhmXLnw5brhc1fnIm/OGyYyf6aH/O+6jMtz8UmX0G3PUJ0WU4mJ4Hvk6Mej6fKXFCUI02FXYB1LTTYEfS+PjkbeASfR+iei8++PjU"
                       + "7y+Q6j0u/1rHPBiXWwtc4hiSuv2l0bWn4mZPBRlrH44Mmenp1ioLRPYdSLhu4lsXZ9/nrv8QcW8XoQwjeQ2oa7/NhyrbJxtq01NfQTKzkbKtqwammQEtKne5UJPKdEObAIZqE+nbhvNtqBXkeRqZ4TrnSekms5Z/S8CC/Q0yx3Xy9bQ4ndhybNIKLxOhKiDimVwRUAUsXC92Qjq6OCgofCtb4jnIXT8pljlMKreitmpZrCdIHjdxxSc1xECM8L4dYaxmD0j2tlLdtBXVFNe/HTIDDrfCMrakagPs5HlytBVC9miNbMHAVq9o8qWy8Ncv+Uo9JduDiOxvYVLs1RbJVZ73dBOVi3VJozKLdKJ3jRny+Qr6bcLIBnmMJ/MlZ5q/AP4JBTue5V34gP339GbH4h3jTcbhQ1Bb+WdrflP9Oc28rvPqJs7f+D5GE/Lrcryf3dB/7UjgV3pfaU4fARHZZuJHzL8XvuR7E4a3L5WkDxG1FLQ3X7UHusdhHGSrwBu6Rk8Y1q3ZhnWLrS4J2iYoTPcyDuX5Tw4/P3z+/nek4mIbv3UAAA=="; }
        }
    }
}
