// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Init : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208080946541_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOVdW2/cuBV+L9D/MNBTW2BnbCcF0mC8C+843hobx0bGDtC+BLTEGRORKK1EufZv60N/0v6FJXWleJGo+0z6EsQi+R3ynMPDw8s58/t//7f+6cVzF88wjJCPz63T5Ym1gNj2HYT351ZMdj+8s3768c9/Wn9wvJfFl7zeG1aPtsTRufVESPB+tYrsJ+iBaOkhO/Qjf0eWtu+tgOOvzk5O/rE6PV1BCmFRrMVi/TnGBHkw+YP+ufGxDQMSA/fGd6AbZd9pyTZBXXwCHowCYMNz64727F9+HN4B+xvYw+Wl7wGElx8oIEEwshYXLgK0W1vo7qxF8Pb9QwS3JPTxfhsAgoB7/xpAWr4DbgSzQbwP3pqO4+SMjWMFMPYJhfNxJz5YxQjpGJOuv7JuJeOkQ0yHxr7wFWnVX+Fr5QP9dBf6AQzJ62e4y5rTStZiVW24ElsW7fhGjOK59UuMHGvxKXZd8OjCglOr2vbs3xyAspsKyVpcoRfofIR4T54KlBvwkn/5O9WhB4yostE2JIxha6KbEAICnVucU76kf94jzwDpE3hG+0SAAmbG/LsQ2UybPkM3qRU9oSBVqiVf4ysvq8VV6HuffVdA4et8vQfhHhLaX7+h4pbquN2i31vaQQ9iou5zXqrrr6pc6quykqqf61Wp0yaanoz+aFSdG31vqGTgufJCG3nAtRZ3If1fZpDfWYutDRjgWWv0L8BFDpNx++mhQrpHrtsbacQpm+r00BM21+/GCZvPlk4TIZ9aRzMJLnY7RBda0n8KHMts+gxtiKinNMtKlxPfxiGek/6F44Qwimaj/28UbCjKbPQ3dNrOR9ynbnM4H/176MLgycfzsf8D9fXdltTfnLUnr11qCrOnXGiK0q+cN1auMYpiycdS1WnrCjath52cQXEdrPUY2zqtW7qX0njblSoFU1TdrdbQeq9CtV7+a6kOx7Jub3wvAPh1lkVsrsWjsFufYu8RhkPST/+e3uV9"
                       + "iNg4ak1QWkVlfViJNJ+F4q4zWT2JOxhGff9k49lp7ib8OZZpO8t87bLa0v/2nC7/BNETdO5AFP3HD51ByRuNegtcMj3V6+ijb3+DxXh/9qnWAzzl/lpA+ggi8hA4zWhKodZarmvM5rTaVJTlkgUTiqQVXixv6zeZOncNllXv0ml71cpopUM8GtPFutwXgw24NUb7xbOF7onLk043TfuUiFTVpwKymDRlp8QySfWkCr2U76jUbpoVs7OZayVWUdm0cu919phsjI5Gvnmvh8Jho4/LvYm49WRFB3DUXe5/h9wq6/b2mh21mZbFnkbHGCuvoysX7Mtr2AfswNB9pbM0ZdU1Jm/OBF28gWz3lgHehrQBc5e+ADemf59KPKxUZ/fITuxyDc7qG1zj+xDgCJGiwZv6BpfQZSdUHIW3MqdSnvAfL6LIt1EiScWd2Ff9VfAH7CxMry5Kla5cuC1uYpegwEU2FeC59TdpgAY0ihVHopGeKlVJnFqiNbnFlHGQwMWFTZIz+g2IbODIU4Jyz6l+oQaI8huzO/0NnQckBAgT2VohbKMAuIYDEdqb2jvWwYKUWHIJA0j1GxNDgZn0Qbw2kbtTUBX42MS29YrTyXpVFf0lnfZonadSaTjHtoVaancEVeDDU0NNx6fQPo0wTEgXrvws2ia5TDqt0PtPpVqoNG1QtajpjkZLTdW/k8LpeDKFxukYYEK72PnNonLCnl8nYd3Railf7mihKt6T5VJ2XbTIxvZtEJ1RE59CY9QM7UF5Ul0pz7ibxao48DbQmpEsVe0FpbwvGslU1TBnWt2TmGBCvvowZhZNVN7v6mRef9nbRegN2Me2Y6gbxBT6WCego9kpaI4mmhRHd06hPqNptXVoejXQrPmHo5rqMUypnGpBmfSgco43gW6mx1W0DaEtitObPHyAfYcvsmKyNltI5CkVWYvyAExlziQFVELlz811WNmBTQMYd7kuAZVabNajLWN7qELivJIGKOa8qRBS"
                       + "n9WgcXE4roTIN0wNQDoIo8biCyUtXzMDJMBxSqiWefUNFle96e2yOFNanAcWY5TUT5p/LU4AZdRsfoi2r8oTA35J13Iym2pPoozOorjuVzSvhiW60ycBaggWyNdFMg/qz0fMTki4rjePX3uwYcbLDmwQ7+BlJtTt2E327LIWF4awhhOabfoIiqB8SVXHBs1m1Hg72pch8k6SQ+TG0Jsz6letMmuad0fm+yOToZjviMazoLqbQT136hz1Nq66gkP5UmrAJo1z3lOD8jvLwgksytarNOA0+7BeaSJT1zcgCBDec5Gq2ZfFNg1T3fywbR8Z6qUYK7syWUWXtaBE/JDqiFDKnvg68AqFEbkEBDwCdr26cTypmqHLm1NTeL6y/HLfKG/E/p81rA/bXdZMxpK5V3S8TNjJ0KF6usitFyyMGLggVL1A2Phu7OGazZC+ffrChAdIv5gjcC8EeBjus4y1XgnMkLZMkhikvWdVtG0EnzmKI0heEQPaRvSa5mPJXjxU4aGaDlxqUNNdXgVMtfGrw+CCPnkc7nNLrDTsU8JKP3+Xul7nMnXXc91aaqDj+qZj6Xf1FJsHqj/f1iMe7oypBnbyUNWS9ohFtKYKtChsj1sE0qhwi8L2uEV0pQq3KGyPm0ZNqkDTkg6IeSikEjQvbI/LhTiqkLni9thZOIUKNys6GAso7PSGNIOakLkEt8kO1rQdyxBW4uUqCxdf0MKwqqZuhykrxbTxeFLhd7lMp0cqQ+qm6sjIQC3VzQ5326EwRFoDpMMQo7R4MLHMHDWNveKx0i/mCGUcFY9Sfh13JuiwhFgqHk8oOqjZpT9I7jfHVBFMCbDJTNM1Hmu+FY8eeQztS0g9TvGSreIA6J63zSb34SXeUdbTStncqs68Kc1OT8fYmSoCgIwk1dB+LJFVXg5U1oy6JwXNeHmMigoyLztih0o6/RarFNSLU3DhtHudnTw3J2uUjqLTKiwpk/+MHHYMvX2NCPSWrMJy+5u7"
                       + "cVFyM5FXuAEY7WBE7v1vEJ9bZycn74QUjx3SL66iyHEPOgdjjNFvMUTs4QvaIebC9wh/xM8gtJ9AKAU79g1oY14LaQ5oO5p0gL25rk5m1h+WT2zmjJ4m0ElesvRNEdgJZXQVmzPRXm89UCXd+//UWVUyvqHMnCbX3tDwQjakoeGFTHlDw/OJ8AbHrua5GxpeSmM3NIFK3hwleJKTbhiDNmsKst5WQpGObChpjDS/NMnEDOA75Qobev2bK+vVQTq0yon6Fw+8/HWYpFVayNaJqPohicmlHllag4k8MxlJmVhKhSYz/kjyJPVWdiFnUm88IX9SS7yDTxB0AMbleLLt9GaWIvPOYJjVLDwIT2endAIcLkFL+iB5hrBHdRBHj7wwfTKvaF54jptl5XgCJTtFkc8aNF6+JjeImRw6RHzSIMfvMv77cIzTHIo0tVFqpUoHZpAaUzx1yEvS2Zgp86Z0TsU0bWKJA09k0iar17SptlShl9OmUZpMWWqfyRx1Zq650nDNpTLGMpxYZebNrNUxIcj0iTk0QYl9kpD0yvUxfVqPI0rjIYc+isLUJvJoyuORvlw5t5xHn8o+PUaojdLV0Mq22DpiWXENNXWuBm3iitpUICoy+ohakQTnnEk0uDIVkaK4mUrqVUgE0s8qbHWovQo2t/tK8LxQR0KX1UAkpCGhBzeDFWyOVshZeZ2k1QHZc+Yu4SekFOArmxfdAZcMoM6jc2hpGCo916bb0SyQioeZAwx4pOwKfeU99rAHTDjC27EybKRucC314RAy67QboGyDxVf+/Yc4QuYcKU3O7IOcIL+H0Qyr85cVzdU5swZJ3CE/UabOJver89TljdC+hGC/QY+hXXEzizrXeOfnLq/Qo7yKcAt1AwlwqA96ERK0AzahxdRpi5JfIcl+HuCD9wida3wbkyAmdMjQe3QrvjPzmuvoJ9lJqn1e3wbJb0IMMYTkQSeVzy3+OUZu+bMGV4q7Mw0Ec8d/gfR7Kkvq"
                       + "3RO4fy2QPkmBtDqgjH3FLuIeeoHLnJZbvAXPUN+3Zh5WOba+RGAfAi/KMMr29E+qfo738uMfLvoh0DeBAAA="; }
        }
    }
}
