// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class GuidKeys : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207202002398_GuidKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1d227kNhJ9D7D/0NDTboB025MskAzaCWZ9SQYbjw23Z4B9GtAS3SaiWyS21/62fdhP2l8IdadIFkVJrdtsXgZjiTwsVh3eSqzq//3nv9ufXjx39YyjmAT+mXW6PrFW2LcDh/j7M+tAH7/53vrpx798tb10vJfVp6Lct0k5VtOPz6wnSsO3m01sP2EPxWuP2FEQB490bQfeBjnB5s3JyQ+b09MNZhAWw1qttncHnxIPp3+wP88D38YhPSD3OnCwG+fP2Ztdirr6gDwch8jGZ9Ytk+xfwSG6RfZvaI/XF4GHiL++ZICU4NhavXMJYmLtsPtorcLv3n6M8Y5Ggb/fhYgS5N6/hpi9f0RujPNOvA2/M+3HyZukHxvk+wFlcIHfSQ9W2UPWx1T010SstJ+si1nXkid8QVb0n/i19oA9uo2CEEf09Q4/5tVZIWu1qVfciDXLenylpMUz6+cDcazVh4ProgcXl5raaOsn/xYATN3MSNbqirxg51fs7+lTiXKNXoonf2cc+ugTRjZWh0YH3LrR8wgjip0bv2j5gv15TzwDpA/omexTAwqYufJvI2InbLrDbloqfiJhRqo1X+Izb6vVVRR4d4EroPBlPt+jaI8pkzdoKLhjHLdbyL1jAnrYp2qZi7eQvKr3kqzKQio5t5uK0yZMT3u/GKpzve8L9Qm5xEms0J7AKqR74rq9kQYcVBnrjj2kCgY2DqmCz52oWpB/aTTdYd/B0ZHA7rCNyfPR4DoNoSaSZR3W0Swr8ZmbMSWWiUWgeVsq13baFhSrE7sooxVcLgSJrijZUXhwWHdadcThrF2a2q6OO7ZpO8TAwl4vVOpFJbFQBFwqxXJtNXyB3cRGr0p5i5dKSaWXkoxyiWOs5fnwm+0s2XED1WPqANYncIrpo/1yHvlC9d91DgRsoJkte20SsmE/XyMAqj++MY89z0KLAzQfd7JiOen+ab9jrDuizeCVqZO1PsZznu7m4Cb5"
                       + "BcVP2LlFcfzvIHJaNs/+27f9HXLp+K32OMcKSL+imH4MnWa0TE7TMZYQ972fjAn1kle9/5xynBtkwitpaye+77Wxq8AWM8wSkftiJB0+3oSaWbCflcWJFGKBqUypSVUylZAlPSuhxHcS96QCvci3KNqNM7t3nlBamVUkG2h3E7O+i+PAJqk8Cs9vzT1Q7+ul76xM3X+Z2kV3ItP2waUkdInNBDuzvpb0adBGyXGpjcylUW/i1BL5eeOzTQ+mePXOpukHtHMU28iRbcv059SfMErjiG2SCHLPmTVphIhPZf4T3yYhcg07ItQ3HUGJgGVT4psLHCYnWp8aGsxEBtFPKItTtirosUlt2w3HSSOqSkf/BhbBfgCJRIXLckAaNYun4Hi1v28aQ31YCilqRJJCymjBUc7PPiVLFQ6SBiLovCUSUys/9Zhc1Tm1x2YrrK4R+QorpAVjax9zJuGs8vsAxAX9x4IuNGjAXtqir+vEGNzUGWgxiz3km2xiDuiolImZO4c70BP86tTM/vnQE+jEmAwFjGUiQs3VOglDZe8rRBuNK7YiTPWFsU6Yk/X6VENJzedFEzIeZUUGZRiDS6ByezQ+AntEdxNkX9D3VFmX8wu2mMtA12UdeH7zFyD4GFwDjGHSdOkJnYRtkscJYgXsfqpooWLaQOcO2MnZjf6dCAfpZAzGQQowabt0nI9AuczdyOpQVgNHuQSX+WXw5Dl+kRfIpM4OU3nfyXZllQNTteeXpjUlVHF5GMLKHZMNYNwVBwmoWlnNJMq8ExqRCheUGVxxdNQAVp4Cw25WV7PA3hY75wbEfGkmSqxqv9OAkrBfBZCtTgaVSy+7EqKYOhqAIAhlZW6QqDlZv4jHFW+6hyuO5BZ++bJH0vCQ5ocWnngZNR+/4ixf14m5vuSbXqC69J7hVr5huVvlyG3WFujS5VC5/hxLU6o7WaCumvyTLT2Usr64qalZYxrH4kA6U1+JldXV7Bozd46ZdMXcHTbc"
                       + "yAPvhcHq0bppWjlqFEqqViQDXUG+mYF4pLiDJWupwVVg6CzgesCvrBqdwM6BgbQhXaKQdaE9+BodfTnZa8u7RhHQYVeAOoYK5I/7sg70xzGzAxknenP/wXOUmS41aihuGpRb//LddpMFjeYPthsgunR7jcKQ+Hsu2jR/stploabn3+zaR3d6GcbGrmlXPKiULdEgYjOo8JY1zSS9IlFMLxBFDyi5BXLueFIxw4NO0ZrivCPbrthoFpWS/+cV9aG3a81SVSn3ivU3GfZp17F6MZFrr5JQYOSiSHVj5zxwD56vOfjC9bMbOzxA9sQcgbtmyMNwj2Ws7UZQhnRQlswg+S7qpm1j+Hz7PYDlFXGcbUwPVB/K9uL3Jh6q6VsUjMqFdPKA3OOWWFlQp4SVPf4ieao7GnTnKLQHMuAnXHVgbnKXShTs1Fw5aUSuffxXYGsvBzSidxxT086LxUl7gIlRFRRnxLyG+n3pN63Cq6P6ACpXR8K1UTqMsFC1S+faIaZXVeibkdabAIaaamtf9Hkc7af+yYzIHcGPaT51zJuR4eCqf5qM+5JwTGupPBgGllJXm+/ZSgxc47HEdy3Yk4aj1WiTPhl2Lw1hCcFlPJ7walZ8hj1I/VitCjRLgU24DVUeiuHl5QoeA7xxAeOUX8x5HPAz+mR2P77FO9p6XCubz2OD2kXyeIpFytZLz6fg4dzm3sbmJHuS+zErYq2Yap6Jk7ged68xxd46KbDe/e6euyT9CFEUuEY+ecQxvQ9+w/6Z9ebk5HshNV+HtHmbOHbcWefOO/jk9wMmyRUX8kiSLxE9Qgj9ZxTZTyiSAgb7RkInSwptjoReTBq33lpX56PqDSuldzNUPIDEp3frjDQ4GYBryYsigpQ07VjAigRq8yDvctI8DdyxKTMoDdW16dMS9Sa5IsXNUNqaMv3PkvQ0VeKdWe6x1Dl2CvS/eujlb73y5vRD6rroy0jKXDgqNDkXzkISzvSml5B8pjeekIhm"
                       + "qOG8WH33H87Dpy3JrnlOEEmsvlLdI1tKn9h54GbQsLlHlhN73CvRyOR5RaqLqAYRoENkEBk1hPj/KjXIDDKBTMguzU2CefBrYYk85rMkTkiq0ZbCLoSadhnsmoJj/DwYUBRIr7QfvZJrTJBG44tLm9GST805Mrrn25g/FzT3hpaa9mLcXBSqYKFx8wwAl4mGTGPxpaWumCpPxVSUMbbhyJSZPvWEHLgl2g5MPtGUeyK7g3FmOQ8Bs3bmzNJG4AJt5Y4eqLH8taY1dfw+mNhBm75C1QwcGQr0qPBzQF0q3mv6BITZNyXAMMl/oWkVDFZvyJJhkCNDp9h2eTRetVk0VO3AYcLKRBlgkg0VtjpeVgVbzIBK8OIl1AQUkSo2BDQBg6thJ8zcwU89UiCmaY4OMM3HohJywPk3jFIAKMPbF5hnQ5dWY1JFDJQ8o+9AGKvbg+bFMBJe6/NQ1AcWmhmku+jebXFVrMfAzDCXhZRtwTBlBZClYZ65KqTEFKN1skUmCvn+NTt/cD+Fzo4/MdlXEMkPo/vYrp08yjLv/cegOAEJEhVFhA/l15gihx1L3kWUPCKbstdsHx+nP1PyCbkHVuTSe8DOe//mQMMDZV3G3oNbI3VykNK1n6bbqMu8vQnTHyI5RhfSe7CI4hv/HwfiOqXcV4qP+gBEckL7GbPnmS3ZgY/i/WuJ9CHwDYFy9ZUHy3vshS4Di2/8HXrGsGzNOqxrbHtB0D5CXpxjVPXZn4x+jvfy4x+QzB/WzH8AAA=="; }
        }
    }
}
