// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class fromShipmentToShipping : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207221956145_fromShipmentToShipping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1d227cNhq+X6DvIOiqu0BnnGwX6AbjFlk77gZbx4bHCbBXAS1xxkR1qsRx7Wfbi32kvkKpM0XypyhpdJi0N4FHIj/+/Pnx9Isf89v//r/54dn3rCccJyQMzu1XqzPbwoETuiTYn9sHuvvmO/uH77/6y+ad6z9bn8p0f0/TsZxBcm4/Uhq9Wa8T5xH7KFn5xInDJNzRlRP6a+SG69dnZ/9cv3q1xgzCZliWtbk7BJT4OPvBfl6EgYMjekDedehiLymeszfbDNX6gHycRMjB5/Yts+y/4SG+Rc7PaI9Xl6GPSLB6xwApwYltvfUIYmZtsbezrejbNx8TvKVxGOy3EaIEefcvEWbvd8hLcFGJN9G3pvU4e53WY42CIKQMLgx6+cGuasjqmJn+kpqV1ZNVMa9a+oRPyJL+B780HrBHt3EY4Zi+3OFdkZ0lsq11M+NazFnl4zOlJZ7bPx6Ia1sfDp6HHjxceWqtzZ/+WwIwd7NGsq0r8ozdn3Cwp48VyjV6Lp/8g3HoY0AY2VgeGh9w50IvYowodm+CsuRL9vOe+AZIH9AT2WcNKGAWzr+NiZOy6Q57WarkkUQ5qVZ8is98W1lXcejfhZ6Awqf5fI/iPabM3rAl4ZZx3Olg95YZGDG3q20u30L2qt5LtioTqezcrGtOmzA9q/3JUJ2r/VCoT8gjbtoK3QmsQronnjcYacROlbPu2F2qZGBrlyr53IuqJflPjaZbHLg4PhLYHXYweToaXK8u1EayvMI6muUpPnMjpsQyMQk0bkvpug7bgmN1ZpdptIbLiSDTFSl7Gg92616zjtidtVNTl9nRxwHdskXbIQEm9rKkPFHlF5XFQhJwqhTTHWO2LAi+2HGo5xJlQOcEZgCwEw/xftVTF+v/JazMt4c4mKTcYWTrO6QChNMMvoPWHPkocjKMK80+/shx7GEbmmug4b1XK35M/hwt9IX+GyWP2L1FSfJrGLsdi2d/Dh6tkEen"
                       + "L3XARktA+gkl9GPktqPldpr2upS474O0Z6gH0fr954zjXIcTXknrI/H9oHVRDXYy3Sw1eShGWuHjDbF5Cw5rZXE4hVhgalPWpCqbKsiKnrVR4juJe1KCQeQ7KdpNM7r3HlA6NatINrDdTZr1bZKEDsnsUYQmG/vXZl3fBa5lGp/K3S7Gu5i3Dx4lkUccZti5/TfJnwZlVByXysj33M0iXtkiP2+CS+xhiq23Ds2+8FygxEGu3LbMf27zCaM0jtnWmiDvgrUmjREJqMx/EjgkQp5hRYT8pj0oNbAqSnxziaN0QxhQwwYzsUEMZMnmVKUKfmxz22bNcdKIqtLOuYVF8DZaIlEZUxuRRu3mKTher/Xb+tAQlkKOmpCkkDM6cJQLBM/JUsWWu4UIuv23xNQ6kDolV3VR16nZCrtrQr7CDunA2MbXhlk4qwxgQ1zQR7P70KAF+9QmfV0lpuCmroFOZrKHol1tzAFDXzIxi3BjD3qCn0Xa2b8cegKVmJKhQGOZmNAIvs7CUDFgAJEGjB7UZOEiOx3YCAafmsDLYyBg+BTMAxrDpOgqljUL26SYAcQKOIBQ00LFtJFWjnCYqh/9exEO8skUjIMcYFJ2FfqcgHJ5wIjloSwHjgsLyvOm6XP8TCXWpXm2mMorBzav1iEo1apNGtaUUOX5RAirCC21gJXHIlRA9URtZlG+v9SYVAYRzODKxb8GsN7rGVazPv0B1rZc+7QgprxVweTzikHmKsKphCg7fQsQBKHMzNFbzabmKR0uedshPbEPdoiJVjWSiC317A5RUBm16Hni+Nz0ibm/5EMqoLv0UblOcTm5WlWfa/cWGE7jULnh4FieUp2wAH3VFhvqGB2S/cUNKu0e0wR1RvKZ+ryc7K72sIR5YMKkKuahiPF6HnjKA3aPdovcaZOscFI9lxj4CtoXj8Qj6ZOt7CPtJs1om8bZ3pjQNO6ANmYC1DFcIH9KlH2g3zqYbR4409vrD675zXypcUP5"
                       + "XbNaplbvNutcQ1U82KwBsdXmGuWDXJ2zeGJtc+XVxTfb7mInP8dYOw3viovqqiQaxmzMEN6yopmlVyRO6CWi6AGl35wvXF9KZrgoL0tTrM3ltiuXVmWm9O8io16JttIMzrVzr1h9026fVR2rh085t5Uq45CHYtX5gIvQO/iBZpMG58/PB/AA+RNzBO5QEw/DPZaxNmvBGdKmTmoGaZ/dbNouDV8sOEdoeYWsqUvTA9nHansxus1DtUW+YVRO4cQDco87YuUaJwkrf/xF8rReGRyTo9CqyICfcNaRucl9wlawU/OBuxW58alRga39FNmK3rNPzTsulnvLEQZGlYLFiHkt+YfSb16H15vTEVyulq10cTqMsNzVSCVD4UGqh4shgLSnHGOgV4lIjNq/DWCs5m98yWw0oO4T52yNmO9cj9lyqo25QXupsy23k4rqDx5LfNeBPZmmo0Gb7Mm4S0QIS1Bo8HjCq0XxGQ6MDGO1Sq2RAZtwG8o8FsOr79s8BvjRG8apPlryOOCXzNna/fgt3rOtp21l83Fs1HaRAnlikqr0KqAnBO42RRCt/SolKaqWJ7Et5pon4qYRte1LQrG/ShOstr94Fx5h9a0TXKOA7HBC78OfcXBuvz47+064gKnH5UjrJHG9Rd+QdAjILwdM0lMGZEfSAPsAHU7whGLnEcWS6maonDCdUmi7nPBkLusZ7HX1rSODYaVLfFLHD7/ApxfK6CSY8xqcYxFAuhLnWMCK63GWQdrTuWJk5IrNeXvHImcN4aKOfrAndKHF4EZQXG4xFmfnujhikURV3xFRon/to+e/Drr3YRhS33lXRlLe5aBCk+9yOJELEwbTS7g8YTCecJHCWN35ZP09vDuPL7vPj8rNoIRTH0sdoPYfov0EzpqMq50/He3cIKH87Lr4+shjLzHpcAX8pBK4P5S0fQFK9hnZpfk2vQx+nZgQfTlT4oykmmwq7EOoeafBvhLy6XXc0En6QbL1QeLwGWTg"
                       + "X6Dse1ottkqAMK3OFjjJMaaM+0uTbs+l056LMsZtODFl5pdey2IQse1A8XWb9jr/AH5uuw8ha+08nKHVsQFlFVt9qLDitaY0tQpWKWzOJ2GpqPqVqhhOjdlF3d0u7tbUCRCrtgnATfTfmlJBySfozHIdAbq0TKBzbAcdOSgjV+Gr9XEq2HJ0UoKXL6EiIAWaWBBQBAyuhp1Rm84PC5LwylSFDgrZT0pyDivMjUSukpw1f3hySnKdcHxWR4wkDx/aEaaq9qjKbyPjtTtS+MT8AgXdkuTYULcNSJWXKdiW1NmTVbKDHFs+rckWzNx/j8nW6wnZ1xDpf5YZYKexVK7SvA92YblkFywqkwjf9q4xRS5bR7+NKdkhh7LXbOGZZOT/hLwDS/LOf8Du++DmQKMDZVXG/oPXWP+nK39d+ZnmvGnz5ibK7v4+RhWyk3OI4pvgXwfiuZXdV4rvkABEuqX4EbPneVuyHQrF+5cK6UMYGAIV7qt2QvfYjzwGltwEW/SEYdvafdj02OaSoH2M/KTAqPOzn4x+rv/8/e/H2iXN4HUAAA=="; }
        }
    }
}
