// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class removedDelivery : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207221948420_removedDelivery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1d227cNhq+X6DvMNBVd4HOONku0A3GLbJ23A22jg2PE2CvAlrijInqVIly7Wfbi32kvkKpM0XypyhpdJi0N4FHIj/+/Pnx9FMf89v//r/94dlzV084ikngn1uv1mfWCvt24BD/cG4ldP/Nd9YP33/1l+07x3tefSrT/T1Nx3L68bn1SGn4ZrOJ7UfsoXjtETsK4mBP13bgbZATbF6fnf1z8+rVBjMIi2GtVtu7xKfEw9kP9vMi8G0c0gS514GD3bh4zt7sMtTVB+ThOEQ2PrdumWX/DZLoFtk/owNeXwYeIv76HQOkBMfW6q1LEDNrh929tQq/ffMxxjsaBf5hFyJKkHv/EmL2fo/cGBeVeBN+a1qPs9dpPTbI9wPK4AK/lx+sqoasjpnpL6lZWT1ZFfOqpU/4hCzpf/BL4wF7dBsFIY7oyx3eF9lZImu1aWbciDmrfHymtMRz68eEONbqQ+K66MHFlac22vzpvyUAczdrJGt1RZ6x8xP2D/SxQrlGz+WTfzAOffQJIxvLQ6MEdy70IsKIYufGL0u+ZD/viWeA9AE9kUPWgAJm4fzbiNgpm+6wm6WKH0mYk2rNp/jMt9XqKgq8u8AVUPg0n+9RdMCU2Ru0JNwxjtsd7N4xAz3sU7XN5VvIXtV7yVZlIpWd203NaROmZ7U/GapztR8K9Qm5xElboTuBVUj3xHUHI43YqXLWHbtLlQxs7VIln3tRtST/qdF0h30HR0cCu8M2Jk9Hg+vVhdpIlldYR7M8xWduxJRYJiaBxm0pXddhW3CszuwyjdZwORFkuiJlT+PBbt1r1hG7s3Zq6jo77tiiLYmBib2ZqPKLymIhCThViumOMVsWBF/sONRziTKgcwIzANiJh3i/6qmL9f8SVua7JPInKXcY2foOqQDhNIPvoDVHPoqcDONKs48/chx72IbmGmh479WKH+M/Rwt9of9G8SN2blEc/xpETsfi2Z+DRyvk0ulLHbDR"
                       + "EpB+QjH9GDrtaLmdpr0uJe57P+0Z6kG0fv854zjX4YRX0vpIfD9oXVSDnUw3S00eipFW+HhDbN6Cw1pZHE4hFpjalDWpyqYKsqJnbZT4TuKelGAQ+U6KdtOM7r0HlE7NKpINbHeTZn0bx4FNMnsUocnG/rVZ13e+szKNT+VuF+NdzNuJS0noEpsZdm79TfKnQRkVx6Uy8j13s4hXlsjPG/8Su5ji1VubZic8Fyi2kSO3LfOf03zCKI0jtkgiyL1grUkjRHwq85/4NgmRa1gRIb9pD0oNrIoS31ziMN0Q+tSwwUxsEANZsjlVqYIf29y23XCcNKKqtHNuYRG8jZZIVMbURqRRu3kKjtdr/bY+NISlkKMmJCnkjA4c5QLBc7JUseVuIYJu/y0xtQ6kTslVXdR1arbC7pqQr7BDOjC2cdowC2eVAWyIC/podh8atGCf2qSvq8QU3NQ10MlM9lC0q405YOhLJmYRbuxBT/BYpJ39y6EnUIkpGQo0lokJjeDrLAwVAwYQacDoQU0WLrLTgY1g8KkJvDwGAoZPwTygMUyKrmJZs7BNihlArIADCDUtVEwbaeUIh6n60b8X4SCfTME4yAEmZVehzwkolweMWB7KcuCosKD83jR9jp/l6TfNs8NUXjmwebUOQalWbdKwpoQqv0+EsIrQUgsYd+wpAdUTtZlF+f5SY1IZRDCDKxf/GsB6r2dYzfrrD7C25dqnBTHlrQomn1cMMlcRTiVE2elbgCAIZWaO3mo2Nb/S4ZK3faQn9sEOMdGqRhKxpZ7dIQoqoxY9Txyfmz4x95f8kQroLn1UrlNcTq5W1efavQWG0zhUrj7H8pTqCwvQV22xoY7RIdlf3KDS7jFNUGckn6m/l5Pd1R6WMA9MmFTFPBQxXs8Dv/KA3aPdInfaJCucVM8lBr6C9sUj8Ug6spV9pN2kGW3TONsbE5rGHdDGTIA6hgvko0TZB/qtg9nmgTO9vf7gmt/Mlxo3lOea1TK1"
                       + "erfd5Bqq4sF2A4itttcoDIl/4MRXxZPVLldeXXyz6y528nKMjd3wrriorkqiQcTGDOEtK5pZekWimF4iih5QeuZ84XhSMsNFeVmaYm0ut125tCozpX8XGfVKtLVmcK6de8Xqm3b7rOpYPXzKuVepMg65KFJ9H3ARuInnazZpcP78+wAeIH9ijsB91MTDcI9lrO1GcIa0qZOaQdpnN5u2S8MXC84RWl4ha+rS9ED2sdpejG7zUG2RbxiVUzjxgNzjjli5xknCyh9/kTzVLYb7cxRaFRnwE846Mje5I2wFOzUH3K3IjaNGBbb2KLIVvWefmndcLPeWIwyMKgWLEfNa8g+l37wOrzenI7hcLVvp4nQYYbmrkUqGwoNUDxdDAGlPOcZArxKRGLV/G8BYzd84yWw0oO6Ic7ZGzHeux2w51cbcoL3U2ZbbSUX1B48lvuvAnkzT0aBN9mTcJSKEJSg0eDzh1aL4DAdGhrFapdbIgE24DWUei+HV+TaPAR56wzjVoSWPA55kztbux2/xnm09bSubj2OjtosUyBOTVKVXAT0hcLctgmjtVylJUbU8ibVirnkiThpR273EFHvrNMF694t74ZIs5l4muEY+2eOY3gc/Y//cen129p1wAVOPy5E2cey4i74hKfHJLwkm6VcGZE/SAPsAHY7/hCL7EUWS6maonDCdUmi7nPBkLusZ7HX1rSODYaVLfFLHD7/ApxfK6CSY8xqcYxFAuhLnWMCK63GWQdrTuWJk5IrNeXvHImcN4aKOfrAndKHF4EZQXG4xFmfnujhikURV3xFRon/toee/Drr3YRhS33lXRlLe5aBCk+9yOJELEwbTS7g8YTCecJHCWN35ZP09vDuPL7vPP5WbQQmn/ix1gNp/iPYT+NZkXO386WjnBgnlZ9fF15889hKTDlfATyqB+0NJ2xegZJ+RXZqz6WXw68SE6MuZEmck1WRTYR9CzTsN9pWQT6/jhr6kHyRbHyQOn0EG/gXK"
                       + "vqfVYqsECNPqbIEvOcaUcX9p0u25dNpzUca4DSemzPzSa1kMIrYdKL5u017nB+DnlvMQsNbOwxlaHRtQVrHVhworXmtKU6tgQWGzVr6tKgZWmwE1Kne6UJXK95o6AWLVNgG4if5bUyoo+WxRiRtoxHWO7aAjB2XkKny1Pk4FW45OSvDyJVQEpEATCwKKgMHVsDNq0/lhQRJemarQQSH7SUnOYYW5kchVKWc9QSW5Tjg+qyNGkocP7QhTVXtU5beR8dodqSI/MAksQNAtSY4NdduAVHmZgm1JnT1ZJTvIseWvNdmCmfvvMdl6PSaHGiL9zzJ9bDeWylWa9/4+KJfsgkVlEuFs7xpT5LB19NuIkj2yKXvNFp5xdjP4J+QmLMk77wE77/2bhIYJZVXG3oPbWP+nK39d+ZnmvGnz9ibM7v4+RhWyL+cQxTf+vxLiOpXdV4pzSAAi3VL8iNnzvC3ZDoXiw0uF9CHwDYEK91U7oXvshS4Di2/8HXrCsG3tPmx6bHtJ0CFCXlxg1PnZT0Y/x3v+/ndTuEjN4HUAAA=="; }
        }
    }
}
