// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class ValidationAttributesChange : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208130838421_ValidationAttributesChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1dW2/juBV+L9D/YOipLbB2kpkC04Gzi6wz2QadXBBnFmhfBoxEO8RIlFai0uS39WF/0v6FkrpQFC8SZcmSPS+DWCS/Qx5+PDy8HM4f//t9+dNr4M9eYJygEJ87p/MTZwaxG3oIb8+dlGx++OD89OOf/7T85AWvs1/LfO9YPloSJ+fOMyHRx8UicZ9hAJJ5gNw4TMINmbthsABeuDg7OfnH4vR0ASmEQ7Fms+VDigkKYPaD/lyF2IURSYF/E3rQT4rvNGWdoc5uQQCTCLjw3LmnNft3mMb3wP0GtnB+GQYA4fknCkgQTJzZhY8ArdYa+htnFr3/+CWBaxKHeLuOAEHAf3yLIE3fAD+BRSM+Ru9t23FyxtqxABiHhMKFeCc9OLyFtI1Z1d9YtbJ20qo/oyiAmLBPYk6a91/wrfaBfrqPwwjG5O0BboryNJMzW9QLLuSSvJxYiEk8d35JkefMblPfB08+5KpaNJZn/5YAVN+0l5zZFXqF3meIt+SZo9yA1/LL3ymJvmBE2UbLkDiFnYXex8jlUi+hiwLgO7P7mP5VEPqDM1u7gAGedUZfxRAQ6N1hLoH+fESBRT1vwQvaZvyQMMu+pUR9gH6WI6Gfcr7Oy9SvNQrMruIweAh9oXgtw9dHEG8hobUMm3Kt6ahxpaouFxX7rDh5NHy82GwQtQQE9gUSddgXa798fYAuRNSWTzIUS+HrNMZTyr/wvBgmyWTy/4OiFUWZTP6KjtvphId0Yo+nk/8IfRg9h3g69X+i3ojfUfq7s97i9zFVcQuqnap46ldhSqsmKk2yMk3p8ugmKZv5NJ8oh5tSy3o0T6lli7rWdk19R9jsAmRZuDRdhes5jE6AlK2XF1BR4ljcgFUYRAC/TTIlTjUVcSt4mwZPMB5Sfv57fFtEF3FxixnKs+gsEEtRBrSUvOtI1g/iHYyjuX6qAd1p7Gb6OZZhO8l4nWju/idInqF3D5Lkv2HsdZRP/+wr"
                       + "fw18Mr7U6+Rz6H6DvL0/h5T2AI/p+UhIn0FCvkReO5rWCDaarmvMBrXeVlTpigmTkpQpXk7v6jzZengtptXs1xlr1clq5U08GtvFqtwXgzW4M0b32bMD9+T5ycRN2zplXaqrE4fkg6aqlJymUE/J0It8R0W7cabMnc1cp26VyWbs9157mdnK6Gj6t6z1UDis9Wm1OJHXnizpADYhqgXwkGtl0+resKS2Y1kaGDjGVHmdXPlgW507fcEejP03OkpzVV1j8u5M4uINZMu3AvAupgWYu/Qr8FP6+1TRYS07OzjzUl8ocNZc4Bo/xgAniPAC75oLXEKfbXgJEt6rmsp1In68SJLQRVlPKpbjq2aN8gl7s5YZqSKw4C3MblKfoMhHLu2sc+dvSmPMwHxSqQPLkKeObCnuMFUKJHB24ZJsO38FEhd4Kt2pZrz6F2pcqC4xO6BcUY6TGCBMVEuEsIsi4DdXXCpma8JYvbgEOeUSRpBSFpPmzrARzf0jVTyXIqmrTTvLhUCrZrYp85CJFeZJqaKFjmmD0qKhOgaW2tJ/J8KZdDIG40wKsJHN3elJKCctpEw9bNqwqvpXWK/Vu/dkPlfnAyOytX0bhDN64WMwRq/QHpJH5Uq1c9jerZptRAvW7MlSNR79qM7mnkxVg3LG5Z6iBBvx9dsLkzBRf3Bm6vSWU7Rdur0NvIFT+Rnfoblrjc0Yg5SNnWRTAeUuzKTMlJZ9bewxrQH1699OK4i2I9l2+h8OO/VtGJOe+o7qws+xuJlvBdAyhJbgK+PyLir7Dl9VYrIya0jKO2H5RdbsWqozqzYXtCZNYWAdSzhtNAK1ghQVWjNVxTokwaFogWJ+lw4hdzctCvPNQi1EudZpATJBWBWWr2wY9VoYDQlOII6uZcW2u5DLsDMvc7l9W4Q3RNKkMizaN0IkKAWkNj5oNgsVqNvBqg6al+p2i3Wh6u3tN66x7XS5gxrkMzZVCU2LR5vlo1B1eWA3aMKwYtwD"
                       + "EbRXJZrUYFgXWa+M+ipEXdQIiEIbemvGcHNN1Y2Fp97BV7dpTQfvXFV3MdMNph9599+soCaHsYvLqFFROT1Y6MngJPZkUXkuwZ0RnrZc5FE0xYflwhBus7wBUYTwVgi/Kb7M1nnszeqHdfdwlyDHWLi1ASu7TlwSCWPKESmV3ePz4BWKE3IJCHgC7Ahl5QVKNkvXq5Sm8cDU/ivn+7IQ+7so2ByLNG8aj5V2r2iDWa6s7VBDA33xGYuOAj6IdeeMq9BPA9zglpvL5+fIIkD+xR6hiHIQIYpP9hjCWaKII3xWsZYLSaPKAkDpTGUlVSeIFX2aJqT+3OnBm/E4U9+uEoGaN7LMiMpOgwjaug1hxh2Cm/U4GxGqntIdkQfP6EB5YndcfhNZh8sTu+PyYBcdLk/sjpsHsehA85QdEMvIFC1omdgdV4g40SELyd2xi/uoOtwi6bu0p5JXPqRRNcQvZLhtVrWh7L7Mai14odZtYkIHM60zAzsMfyXAQMRTEr9LkubL3yG5qVveW9BSX+xwnUONUetszOQb8yKYnNbB5cjuwdf8jOyLPUJ1p11Eqb7udySYsKR77SKelHRQo8u86ddvjOluk2fANiPNVHhf443flRIxjBeozDj8AkzNmTDdipms34fv8R37etxetreqEy9xi12ufaxzNZexrXqqpfy+uqx20qhbm+6IV94X1kGWaUfsUCm7lHIWLp3vVkq7kstih7D9pSBlyzDPwt7bCF+Qx7YL128JgcGcZZivf/NXPsp2kMsMNwCjDUzIY/gN4nPn7OTkg/S+0A5v/yySxPMP+wGgFKPfUojYSTnaIObD94hFwS8gdp9BrESe9Hk7xdv7Wz/MKSLtsQtH8YBO7/7UPabTG9TwsE5v3P0SRffIzlAUN7yhMzS89C7B0PDSCzhDw4sP3AyOXX+/Zmh45XmaoQXUIti14Fm8+qHZxkmfFeltbzRPjAzVr3saqYYHQizgd3r/Y2i6TPWSxUG6"
                       + "RfsZ8vo3KUr4vwTg9a+93pnohyS/HfHEohZHMmoqkvbdCB2aOniO5BmE3sSXnkTojSc9j9AR7+Dj/w/A0BxPMP1g65B9YNaD7BEez06ZOnCgkLNJI8yqu34TxJONGgrxfQeL5Rdap4jfmpZLLfcCJ6bTYQR5WQZN59fmO0cy72zRtJHWOz/eMG4o6oGHPnd5B2Tcxzl0ETLjPrwwGlkaT8iP+i2PqR7umIoy1n04MmWmfYtjx9jh8WN4DXEjfeKVe/kq40cAH1HErxqdInemPqg093OrhZrWDc6PrenC7ymkvZ8v+MQcapSQSVxjVHCTmHYRgsOkyBDSdEJ4cruUfKZXBOSfddj6KEUdbGmLteBlokmEKSBUFmQQYQa3g5XsgLGTi/SmntbHsU0RulmLiDOGnBusteaC0DFEZIr2QA0Bm7LpAwYqi4O4usJsFXxrx4kdmjd4RH63BqoGSL5x2r+Je4i4V8LrJ2/kCDHBViOsyYHTFNe/HTFIsK96XY56P8J/v0d9sARtKwj2n/Fh6Nb8Hp7nGm/C0geTalRmkbavbyABHnWKLmKCNsAlNNmFSZK9Tlw8G/opeILeNb5LSZQS2mQYPPk1Z465cU3ys4jmep2Xd1H2VuwQTaDVRGzT/Q7/nCK/eu70SrPpboBg/uEvkH7P+5K6mwRu3zjSrRIgZgIq1Mfd2kcYRD6bse/wGrxAc93adVjX2PISgW0MgqTAqMrTn5R+XvD64/8BwAC+DEByAAA="; }
        }
    }
}
