// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class init : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207192228529_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOVbW2/bNhR+H7D/IOhpG1ArSTugK+wWmZNswZoLorTAngpGoh2iEqWJdOb8tj3sJ+0v7FAXWhZJiYpvcfMSRBL5nQsPeUiez//98+/wwzyOnAecMZLQkXs4OHAdTIMkJHQ6cmd88uqt++H9998NT8N47nyu2r0W7aAnZSP3nvP0neex4B7HiA1iEmQJSyZ8ECSxh8LEOzo4+MU7PPQwQLiA5TjDmxnlJMb5AzyOExrglM9QdJGEOGLle/ji56jOJYoxS1GAR+41aPZnMsuuUfAVTfHgJIkRoYNTAOQEM9c5jggCtXwcTVwnffPuE8M+zxI69VPECYpuH1MM3ycoYrg04l36xtaOgyNhh4coTTjAJfRJfnClhWBjrvqjUCu3E0wsTBNv6g2h6R/4cekFvLrOkhRn/PEGT8ru0Mh1vOWOXrOn7FfvJCSO3HPKXx+5zuUsitBdhKWrwJc+TzL8G6Y4QxyH14hznEE4nIc4t2FZ7NBbWGZj73VGghdlsI9piLOXZPENDjB5eCE2+/ckjQHhRRnrw6o4Yy/CZEgsex3IqhDxt5ICORMyreuckTkOP2I65fdS0gWaV29+ho3AJ0pgxwB9eDbDGsXahf6O2L3QlbG/kyzsKR7+XVW+jyK+fanjDIshuqKV6BN4vCVxf6SPiPFPadiNVujZALtED2Sab2QasCK6z+lNEok91Q2O8jYMZnmxtRosvn/JJ4JzliWxeKx3zT99uUXZFAsfJ/rvPmznArzCLCzAvq25KOyyENQOItzSH6Q1JlYNhmqwTcFQBYutTvnI63SSkDKKF0o1vykhqjRYKUa/vejcTqZ48uLUa+ybEWkMDpuxP2YsCUiuj6LrF82O4ZSGTsdEKZy8PM3As7OIkzQiASgxcn9SfGcGlrG+DNyEPHSbAXpFT3CEOXaOA55fA4wRC1Cojhv4Jlx+AzGNMxFaKILDPuMZnNm5OgEIDUiKonbFG91sZ47QS0po"
                       + "fjnBqTiMUd4+GDai5cKtipdSGu7q8s7Qq4VVe7QpkW+KCvM0WISFLtLWGhYt6hii1Db8nxRwJp9sI+JMDrCRLdP8FkKuWPagD4ceOCs1qK7fxHs8bx55iz4+5uoFFyzNi4W0HOf6/Ze6rGmh8rujFqzibskSrLiXaUErL24s4apLjxZAeS/SBVkds3VY8r7BFqQ4q2vd1jjOdyGKuNXBFHnForPM01qIatJ3AJkgtJ1r4a1TpdzH1loZtrrNGded0KXaDdOVydudwhtQ6kB5y2ZauEDdOqk+aE8ydmmmpnq3/cbsYOfLFjdU+zi5oC1qD15RfKiKFJ6hSjG8QGkKG+Ba1aJ84/hFyWL8yu9fJYgLDC9gmmKB1FZKgu08rCONryAaND0jGeMniKM7JPbY4zBWmlku35U0zSqujl01CatO4v+yY3sJZ2Csf9Sdewb2ihUqNx3X4qC1d15SQhHKdIemcRLNYtqSzkUUNMQrCVcxXNkDLTuzj6vLLLcBX2tqL32cbei+396utgEbcLeu8tPH36b+++3wxUZpAy7Xl576ON2MsKduX2wm1+lvfdnLytHmrnvuYbnT3oSjdSW3Xu42Aeyp04ud8Do9rdvoW/hX321Vr5r6F1eydYDijT1CsxJXx2p+s0ct6mt1rOKNPUKtVlaHqb22x2pUy+p4jU/PKp7NB63VolpXOcuBbWLb1HlTES5vVusYxutWM468LqvjGO/Qdjbu6x/xJ471dkfZfh3b6LgoFwPNJlK6vCBoXAQMy0N5N6dROaUXTVwHXPNAQnFC9x8Zx/FANBj4f0XjiOQ3fVWDC0TJBDN+m3zFdOQeHRy8bTAhn8BS9BgLo2dNVSTCB52lzNYy496wFHdg6+4IijswdpfcxG2au0ta4i7s3B0jcZvW7oqMuAYbVfw6u4Q+oCy4R5nCJVkLzbBC/yFG8x9Xog6uhqTQAcUxhK+NDqhDU+mAe8K520jINeh2uYzVyHbdEM+eP/ZM"
                       + "J/dmuFfbJUTparvbJbsYLrU2yaX61vhTuyJL7SpkrMdwyyGze/6TWmc3XPFozs0dBKjiLgBy+F0Co10sissEqh4UqU6GVIu0imPVh0TVzaFqESh5WP14VjY0qxapNbqWJY+qlYulk1RjcfWialkQtdrE9SBzGblcOnw99UgHW61OWvDqo0mEidzTFGQQYQbXw26HIKZQmCx5YAbq0/MkgClsr60Z2YPepd7WQpao/U4dkhQj0wWE+NU6xcFSfpBtzukkqfJUQ6OqSWNbfIE5gmMaOs44maCAw2dYbVn+y4rPKJpBk9P4Dofn9GrG0xkHk3F8Fy0lPZHu2uTnHLZlnYdXaf7biXWYAGoScdK8or/OSBRKvc80W3gDhMij5VlDjCUXZ47po0S6TKglUOk+mf5vcZxGAMauqI8esFm3bh8ue2x4QtA0QzErMRb94RHCL4zn7/8HU2bIeWlBAAA="; }
        }
    }
}
