// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class PackageReceiverRemoved : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208061330456_PackageReceiverRemoved"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOVdzW7kuBG+B8g7CDolAdbt8UyAyaC9C2/b3hgZjw23Z4CcDFqi28JIVK9Eee1nyyGPlFcIqV+Kf6L+1buXwbRIfiSrisVikVX+33/+u/7pNfCtFxjFXohO7XdHx7YFkRO6Htqd2gl++uGj/dOPf/7T+sINXq1vRb33tB5pieJT+xnj/afVKnaeYQDio8BzojAOn/CREwYr4Iark+Pjf6zevVtBAmETLMta3yUIewFMf5CfmxA5cI8T4F+HLvTj/Dsp2aao1hcQwHgPHHhq35KR/TtMolvgfAc7eHQeBsBDRxcEEHswtq0z3wNkWFvoP9nW/sOnrzHc4ihEu+0eYA/49297SMqfgB/DfBKf9h9M53F8QuexAgiFmMCFqBMd7HKGZI7p0N/osNJ5kilmU6Nf2Iqk6r/gW+0D+XQbhXsY4bc7+JQ3J5Vsa1VvuOJblu3YRrTHU/uXxHNt60vi++DRhyWlVtr29N8CgJCbMMm2Lr1X6H6GaIefS5Rr8Fp8+TuRoa/II8JG2uAoga073UQQYOjeoKLnc/Lz3gsMkL6AF2+XMpDDzIl/G3kOlaY76Ke14mdvnwnVEVvjgeWVdRmFwV3ocyhsnYd7EO0gJuMNGypuiYw7Lca9JQMMIMLyMRelqvHKyoWxSivJxrleVTJtIunp7A9G1JnZ94ZKJ14IL3S8APi2dRuR/+UK+aNtbR1AAU9ao38DvudSHrdfHjKke8/3eyONuGQzmR56wRby3bhgi9XSaSEUS+vQFsEWIhdGf5gVdQcd6BFraZbdruh8m0Rozv7PXDeCcTxb/7dhjDcEZrYBbMjana/zkNjO0Xz930Mf7p9DNB/5L4jB77fs/f1J++6b9ptM9+l2nKzGA2OaCRsOX0VlIAr12tqHTZtkJwuR3xy1ZmRbS3ZLDlgKE7xWpSSKbLj1GkqTlqs2hFGbi8ehbOjkmNx7H59lW5xrO5xsG1QuFMoy6fKgBQ81Mayp"
                       + "HkmxsDBkdYY9kvbQkQqbXKlLOy3jlLqHsnpnWXldNmLyX0232W99r/8E8TN0b0Ec/xZG7qDdm+kb4OPpe72KP4fOd1jO9+eQSD5AU56/OaTPIMZf924zmpSpWqV2hei6lquNqvwh0391vcYUSXUaW97RhCo16jCal1dmOu3cWZFl0z4YdTaEMUIn3Bqj215rKI8yTsvk1XRMKUtlYyohy4VUDYovE1aJUKGXMXxQYjfNLtpZ9bViKy9sSr738lem56aD4W8x6qFw6OyT6gTAn0xp0QLc49XxeMiTtOrorzhwm0lZEihkjJLyKr70wa66uv1K90b/jazSjFRXCL8/4WTxGgaPMMoBbyLSgJpQ34CfkN/vBBrWqtO7ZzfxmQYn+gZX6D4CKPZw2eC9vsE59KlDi+nhg0ipjCbsx7M4Dh0v5aTkHq3mwKl3foFcy/S6oxLp2iWddZ342Nv7nkMYeGr/TZigQR/ljiP0kTmd6l28s3ltcoMI4SCG1pmDU5/+BsQOcMUlQajn1r8QBUTojeg7gA1ZBzgCHsKitvKQ4+2BbzgRrr2pvqMDLLviS87hntp+CBsyzGQM/DWLOJyyV46OTWRbrxiZ1Isqby+ppEdpPFVCwxi2LcRSeUqoAy9PDBUDn0L6FMww6bo05WeRNsFkUkmF2n6qxEImaYOKhWY4Cik1Ff9OAqeiyRQSpyKASd/lyW82Bce7AHS6SOkPmFAf6Uek3q+LK7BRxE9DnKl0noISy9d7Kud6g62m9rQbsn4kqWy8LBUPYCMJZQOhJjQFVcRoYQkyr3dmkVLpnbNKBvQX0F0EoAH70I4puklMIZc6Bh3M8UThD2kSHJVzRO4YanVeaXrJ0Cz5yxFN+RymFE45o0xGUHMeTiCbmY+MtMGkRekyKuIc6Hf4KgombbOFWFxSsW1VXjeZOhMEUApVvItXYeVeogYw5rZfAKqk2GxE5TWbakiFpdIARw02GUpmfBs0Lr3yUojipNYA"
                       + "pIIwalz3mEpxODXEATKiKOd8/XUYU73pqTW/Xlq4IstZCkIorMIWzkcRNV8lvAas08SAXsKNoEgmrRPMyA3GDL8mexqSqBxfHNQQJBBvqkQa6F0zZs4ZZujN81f6VMxo2VEShNcAcmnQegyMfQZNrDQ+6ouroxx/b6ooH34p1Yn+GNvqIGs8sVbnTwaVmU9vSsnf5Ipkaj5HmZ+kTKZifnYaT8uqLi7V1NGZ9G2MegmFqg3XgFAKQ76nDBWXqqXBWJatV1kUbf5hvVKE266vwX7voR0Tfpt/sbZZ7O3mh237cNcgw1g5tWXLm7dlTziMiJRwpaRrMtJLL4rxOcDgEdD7340bCNUMzeOiN4mVLPKvsKCKRvT/eUN9LPKRZjlWxL0k86XMTqcO5QtGbG3R2Gjgg0j2RGIT+kmANAcndfvsCQwLkH0xR2CeMLAwzGcRa73iiCEcrwQ2COfUOmvbMD43J0fgvCSwtQ3rFc3H4j3vgGGhmpwzGtTsRFgDkx0SdRhMJCuLw3xuiZXFsgpY2effpazrjKfucq7aTQ1kXN10ZPlmvN4SCdf4xBuRF7hy6hGrLFS9pD1iGXcjAy0L2+OWcTUy3LKwPW4VNioDrkrbI2fxoDLUrKQDYhHkKQUtCtvjMsGbMmSmuD12Hg0iw82LFqMLG8/avTd+WfBfim2486vaj6Uay9tqFkN5ha3G6W8+StVKB3UiVSMa9TGTKGZumiElUOZQNBA8ebPlHjMk6kapZlQYfCgZC8aXtZDgNECsJr7pF3OEKtiLRam+jmugqrC4gC8Wjyta1OpSu5f7rTFZSFUKbLLSVI2Xrt/Lp3W1bV713m42vg/P8Y68npbL5lp15kNo6S8d4ywqiUky4lVD+7GYVntXUNs1dA8OmvGKsBkZZFF2wJ4Owd/NVyl7L/3enH97nfuam3NOCs7nrArNKxW+eC51PG/fYgyDI1rhaPurv/G99DaiqHANkPcEY3wffofo1D45Pv7I"
                       + "ZarskEVyFceuv+hUkgnyfk2gR5/FeE8evQvvEZGJXkDkPINIiL/sG2NH7RbcHGN3MFkNe1Ndno+tPyybm80dPduhm75w6ZvpsBPK6CI2Z77AocRLyB34x5RbWU7BoVSdImXg0PBcKqSh4fmEf0Pjs/n8Bseup+sbGl7Ixjd0B7UcP1LwNLXeoBvnfJnTeqsKLnHJIu2fkZTBIEpg8dm5FslR6SL9SwBe/zpMci0lZOuEWf2Q+CRYjzTVwkSmmYgkTYAlQxMJfyC5mxanDrmcTi3xFp+0aAHK5XAyAPUmliQb0GCY9cxAHppOT6kYOFzSmOwV8gxRkfLojh65avpEACsedY6b+eVw4ih7BaDPHm9ePSc3CK8cI7J80pjI323I+HIU1owCNZmi6iJO8yqptqla5krK0lE5DpiHZfrEFgeQZKVNKrM58/kUoceKiOTDFhrtU5ylSUyrdGRz5R6bS2SMeTixyMybTqxjQpLpE4MoAh37JEHplWtk+rQiB5RGRAyn5JmpTCTSlEckextzaruPIeF95qfQxv4q+srP8KrO8mJNb/IsEcqkGdpUJLJu1FG6ihkVVppqSkW5Zk6qKHy+x8zCEDrKPsvw5ZkfZLDFHiAFLwpVXahyK/AdKbpQg5vBcvpHyfC8XMf14q9TcT3OmEGFXZxCALGoalTeNBFAntNnyYkf1HketITgVUE9TrE/AUbK59CX/2NPe7Q0KELCExMxbyshS8gA1G6iopbm4w76T3GEDD9COp/ZJzlBjhGjNaezriXN5bm9BkkdIj6ZJqZpgui9VPbrHMberoJYE0wEnZpRWta5Qk9hYSBzIyqqcJdi1xADl1isZxH2noCDSTEx8eL0D7Xkf0HhIniE7hW6SfA+wWTKMHj0a5Y2tbF1/af5UepjXt/s0z+bMcQU0gemhD836OfE86u//HApucpTQFDj/RdIvme8JGcBDHdvJdIXIYBXBZSTrzxz3MNg71Oz5gZtwQtUj62Z"
                       + "hnWKrc89sItAEOcYVXvyk4ifG7z++H+aEzVnjoIAAA=="; }
        }
    }
}
